---
# set at iso build time
initsys: none

user-services:
  - name: dbus
    action: enable
  - name: pipewire
    action: enable
  - name: pipewire-pulse
    action: enable
  - name: wireplumber
    action: enable
